### ISSUE TITLE
Use driver codec for Instant, LocalTime, LocalDate, and LocalDateTime [DATAMONGO-2017]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2886]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAMONGO-2017](https://jira.spring.io/browse/DATAMONGO-2017?redirect=false)** and commented

We should investigate wether we can use MongoDB's codecs to convert JSR-310 types instead our own ones

---

**Issue Links:**
- [DATACMNS-1349](https://jira.spring.io/browse/DATACMNS-1349) CustomConversions should allow for selective registration of default converters
 (_**"depends on"**_)
- [DATAMONGO-1175](https://jira.spring.io/browse/DATAMONGO-1175) Mongo driver 3 codec facility might not be used

- [DATAMONGO-2014](https://jira.spring.io/browse/DATAMONGO-2014) Millis precision vs. nano precision of java.time.Instant on Java 10+

**Comment by mjustin** [comment]
Every so often I get bit in my tests by the fact that the timestamps returned by a persistence operation and a subsequent retrieval operation can be different, due to the fact that the former returns dates with sub-millisecond precision, despite the fact that they're only saved at millisecond precision.  I believe this is the current ticket for this issue.

**Comment by christophstrobl** [comment]
@mjustin sounds more like #2883. You can use `MongoConverterConfigurationAdapter.useNativeDriverJavaTimeCodecs()` (#) to operate upon the driver `Codec` for `java.time` types.

**Comment by christophstrobl** [comment]
solved by `MongoConverterConfigurationAdapter.useNativeDriverJavaTimeCodecs()`
