### ISSUE TITLE
Add an option to @Field annotation to control property write rules [DATAMONGO-2551]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3407]
**[isopov](https://jira.spring.io/secure/ViewProfile.jspa?name=isopov1)** opened **[DATAMONGO-2551](https://jira.spring.io/browse/DATAMONGO-2551?redirect=false)** and commented

In mongo it is possible to completely omit writing a field in collection if it is not needed in this document. This has a benefit of using sparse indexes on such field (or their modern replacement indexes with partial filters on exists=false). Also it reduces storage size. It seems that it would be beneficial to have an boolean option for Field annotation named omitNull (or any other name) that will allow to skip writing this field if it has null value

---
No further details from [DATAMONGO-2551](https://jira.spring.io/browse/DATAMONGO-2551?redirect=false)

**Comment by christophstrobl** [comment]
The mapping layer by default does not write `null` values to the resulting `org.bson.Document` (see: [MappingMongoConverter.java#L615](https://github.com/spring-projects/spring-data-mongodb/blob/3.1.5/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/MappingMongoConverter.java#L6150)).
In some scenarios is might make sense to allow persist `null` values, so that an `$exits` operator would still match, though the actual value is `null`.

On field level something like the following might make sense.

```java
public @interface Field {

	// ...

	/**
	 * If set to {@literal true} {@literal null} values will be omitted.
	 * Setting the value to {@literal false} explicitly adds an entry for the given field
	 * holding {@literal null} as a value {@code 'fieldName' : null }.
	 * <p />
	 * <strong>NOTE</strong> Setting the value to {@literal false} may lead to increased document size.
	 * @return {@literal true} by default.
	 */
	boolean omitNull() default true;
}
```

Same could be applied to the `@Document` annotation or set via the `Conversions` API.

Happy to gather/discuss requirements & thoughts here to get a clear picture of the enhancement.
