### ISSUE TITLE
LocalDate properties depend on the machine's timezone setting [DATAMONGO-2627]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3482]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAMONGO-2627](https://jira.spring.io/browse/DATAMONGO-2627?redirect=false)** and commented

When storing an entity with a LocalDate property in a Spring Data MongoDB Repository, on reading the entity the property's value depends on the system timezone setting.

LocalDates have no notion of a timezone, they are just a combination of year/month/day , so the value should not change.

I have linked a GitHub repo with a small demo application, in short:

```java
Person margaret = new Person();
margaret.setId("1");
margaret.setName("Margaret Hamilton");
margaret.setBirthday(LocalDate.of(1936, 8, 17));
LOG.info("This is person 1: " + margaret + '\n');

LOG.info("Storing person 1 on a machine in Berlin\n");
TimeZone.setDefault(TimeZone.getTimeZone("Europe/Berlin"));
repository.save(margaret);

LOG.info("Retrieving person 1 on a machine in Los Angeles");
TimeZone.setDefault(TimeZone.getTimeZone("America/Los_Angeles"));
Person person1 = repository.findById("1").orElseThrow();
LOG.info("This is person 1: " + person1);

```

This stores a person with her birthday in the database with one timezone setting and reads the entity with a different timezone setting. The birthday is then one day off.

```
2020-09-16 19:52:03.458  INFO 23828 --- : This is person 1: Person{id='1', name='Margaret Hamilton', birthday=1936-08-17}
2020-09-16 19:52:03.458  INFO 23828 --- : Storing person 1 on a machine in Berlin
2020-09-16 19:52:03.696  INFO 23828 --- : Retrieving person 1 on a machine in Los Angeles
2020-09-16 19:52:03.719  INFO 23828 --- : This is person 1: Person{id='1', name='Margaret Hamilton', birthday=1936-08-16}
```

---

**Affects:** 3.0.4 (Neumann SR4)

**Reference URL:** https://github.com/sothawo/spring-data-mongodb-localdate

**Issue Links:**
- [DATAMONGO-1026](https://jira.spring.io/browse/DATAMONGO-1026) Joda, JSR-310 and ThreeTenBp converters are timezone-sensitive

**Comment by mp911de** [comment]
The issue is somewhat related to relational databases. `java.sql.Date` is millisecond based while the majority of databases use zone-less dates. True timestamps (where `java.sql.Date` or `Instant` is the right type) are not so widely used. Since our JSR-310 support originates from JPA/JDBC, we always used a `Date` as interchange. Now one can argue whether `LocalDate` should be a string in MongoDB or a date (or even a subdocument). Both representations come with their own properties regarding sorting, querying and none of them is ideal.

That being said, we are required to inter-op with a driver-native type, hence timezones make an impact here. 

Looking at the docs (https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.custom-converters.xml), we already have documented the impact of timezones. Can you @sothawo check whether that's sufficient?

**Comment by sothawo** [comment]
The documentation you link to is alright, but the table at https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mapping-conversion has a footnote for `LocalDate` that explicitly defines UTC. That's in contrast to the default converter implementation.

**Comment by christophstrobl** [comment]
I agree that the conversion should use an `UTC` based approach that can be configured by using MongoDB's native JSR-310 support. Created #4460 to update the documentation in that regard.

**Comment by sothawo** [comment]
Almost forgot I had opend that issue 😁
