### ISSUE TITLE
java.lang.InstantiationError after upgrading to Spring Boot 2.4.4 (spring data commons 2.4.6)

### ISSUE THREAD

**Issue by svpr3m0** [spring-projects/spring-data-mongodb#3608]
In a Spring Boot application we use Spring Data Mongo to map some documents. Some of them have embedded documents with a hierarchy, e.g.:

```
@Document("projects")
@TypeAlias("project")
data class Project(
       ...
       val budget: ProjectBudget)
```

```
abstract class ProjectBudget {

    abstract fun getCurrentBudget(): MonetaryAmount?

}
```
```
@TypeAlias("projectProjectBudget")
class ClosedProjectBudget(... ) : ProjectBudget() {}
```

Up to Spring Boot 2.4.3 when retrieving a Project instance the corresponding ProjectBudget subclass what built correctly. However after the upgrade to Boot 2.4.4 we get this exception:

```
Caused by: java.lang.InstantiationError: xxx.ProjectBudget
	at xxx.ProjectBudget_Instantiator_srp3na.newInstance(Unknown Source)
	at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:238)
	at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:87)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:344)

```

There seems to be a regression when instantiating subclasses.

**Comment by mp911de** [comment]
I entirely missed the fact of the custom Mongo configuration `MongoDbClientConfiguration` hence I relied on Spring Boot to perform the entity scan. 

I moved the ticket into Spring Data MongoDB. The difference comes from #3592 where we removed `@Persistent` as marker annotation from the entity scan in Spring Data MongoDB. Previously, this arrangement worked because `@TypeAlias` is meta-annotated with `@Persistent` and so entities annotated with `@TypeAlias` are picked up as entities during the scan.

On a second look, `@Document` is `@Inherited` so this annotation should be visible on subtypes. I need to check why the component provider doesn't pick up these types (probably related to how ASM class metadata is read).
