### ISSUE TITLE
When using the query method, can add a custom query search strategy.

### ISSUE THREAD

**Issue by ddaaac** [spring-projects/spring-data-mongodb#3641]
Hi

I have separated the domain entity and the db entity. And I created a repository with a domain entity. And I put a custom converter to convert between the two. Domain entity has wrapped property `MyDuration`, and Db entity has flattened property 'startAt', 'endAt'.

```kotlin
@Document
data class DbEntity(
    val startAt: LocalDate,
    val endAt: LocalDate,
    val _id: ObjectId? = null,
) {
    fun toDomain(): DomainEntity {
        return DomainEntity(
            duration = MyDuration(startAt, endAt),
            id = _id,
        )
    }
}
```
```kotlin
data class DomainEntity(
    val duration: MyDuration,
    val id: ObjectId? = null,
) {
    fun toDbEntity(): DbEntity {
        return DbEntity(
            startAt = duration.startAt,
            endAt = duration.endAt,
            _id = id,
        )
    }
}

data class MyDuration(
    val startAt: LocalDate,
    val endAt: LocalDate,
)
```
```kotlin
@Configuration
class MyMongoConfig {
    @Bean
    fun mongoConverter(mongoDatabaseFactory: MongoDatabaseFactory): MappingMongoConverter {
        return MappingMongoConverter(DefaultDbRefResolver(mongoDatabaseFactory), MongoMappingContext()).apply {
            setTypeMapper(DefaultMongoTypeMapper(null))
            setCustomConversions(
                MongoCustomConversions(
                    listOf(
                        Converter<Document, DomainEntity> { read(DbEntity::class.java, it).toDomain() },
                        Converter<DomainEntity, Document> { Document().apply { write(it.toDbEntity(), this) } },
                    )
                )
            )
        }
    }
}
```

This works well because insert query is not wrapped.

```kotlin
interface DomainEntityRepository : MongoRepository<DomainEntity, ObjectId>

@DataMongoTest
@Import(MyMongoConfig::class)
class DomainEntityRepositoryTest(@Autowired private val domainEntityRepository: DomainEntityRepository) {

    @Test
    fun save() {
            domainEntityRepository.save(DomainEntity(duration = MyDuration(LocalDate.now(), LocalDate.now())))
    }
}

// insert query looks like below
// { insert: "domainEntity", ordered: true, documents: [ { _id: ObjectId('608c098a9fd6863786d30e3b'), startAt: new Date(1619708400000), endAt: new Date(1619708400000) } ] }
```
The problem arises when using query method. If the property of the domain entity is used, an invalid query will be sent, resulting in an empty result. If the property of the db entity is used, an error will occur.

```kotlin
interface DomainEntityRepository : MongoRepository<DomainEntity, ObjectId> {
    fun findAllByDurationStartAt(startAt: LocalDate): List<DomainEntity> // always empty result
    fun findAllByStartAt(startAt: LocalDate): List<DomainEntity> // PropertyReferenceException: No property startAt found for type DomainEntity!
}
```
I am aware of @unwrapped, but that is not my solution. I want the db modeling and domains to be completely separate.
So like custom converter, I think we could add custom query property strategy. Or is there any proper solution for this case?

**Comment by kioyong** [comment]
Hi @ddaaac  can you try below solution for this case? 
because MongoRepository<**T**,ID> interface query method base on  T entity to generate query, you can use @query to custom query  for search **DbEntity**
```kotlin
interface DomainEntityRepository : MongoRepository<DomainEntity, ObjectId> {

    @Query(value =  "{ startAt : ?0 }")
    fun findAllByStartAt(startAt: LocalDate): List<DomainEntity>
}
```

**Comment by ddaaac** [comment]
It may works but... 
I think it is natural to to apply the conversion before parsing query, if there is a `Converter` for a top-level entity(In this case, DomainEntity is top-level entity and it has `Converter`).
Do you have any plans to support this in the future?

**Comment by ddaaac** [comment]
It works but...

Query method is a convenient function that does not require writing queries, and I opened this issue with the idea that it would be better to support converters for query parsing as it supports converters between entities or fields.
Do you have any plans to support this?

**Comment by mp911de** [comment]
Registering a `Converter` for `DomainEntity` entirely bypasses the object mapping part and it is a signal to Spring Data to not introspect the model as conversion should be handled by your converter. 

Spring Data MongoDB is one of the few stores that still allows query mapping for simple types and that is, why `MongoRepository<DomainEntity, ObjectId>` can work to some extent.

By using converters, Spring Data has no knowledge of the actual transformation that is happening within the converter. Therefore, Spring Data cannot transform queries in the way the converter is handling the conversion.

The code works as designed. Query methods are resolved against the entity type referenced in the repository declaration which is `DomainEntity`. Query construction for `findAllByStartAt(startAt: LocalDate)` fails because `DomainEntity` doesn't specify a `startAt` property. `startAt` is declared within the `duration` property.

The query `findAllByDurationStartAt` can be created as it follows the design of `DomainEntity`. The results are empty because the actual MongoDB query looks like: `{ duration.startAt : … }`.

Converters are bound to input and output types therefore there's no possibility to express your transformation. Given that your arrangement over a data store entity through a converter (that is hiding the database entity from Spring Data) isn't a common approach, we rather recommend moving the object transformation to a different level and using Spring Data as it was intended.

**Comment by ddaaac** [comment]
Ok. I understand. Thx for kind reply :)
