### ISSUE TITLE
ISODate format question

### ISSUE THREAD

**Issue by linrong** [spring-projects/spring-data-mongodb#3654]
i have data in mongodb like:
```bash
{ 
"_id" : "b8261207-3f95-40ca-bd05-e06ad451dff8",
"updateDate" : ISODate("2021-05-18T09:17:28.409Z"), 
"isDelete" : false,
 "name" : "test",
 "receivedDate" : ISODate("2021-05-15T09:38:52Z"),
 "deviceId" : "55118b35-43d3-4700-b8be-41daefb7f502",
 "createDate" : ISODate("2021-05-18T09:17:28.409Z") 
}
```

I user spring-data-mongodb in my spring project and code like:
```
    public List<HashMap> findAll() {
        return mongoTemplate.findAll(HashMap.class, Constant.collectionName);
    }
```

i have two questions

1. Because the data stored in my document is different, so I cannot use entity classes for data serialization，
Now I use hashmap to read different data
Are there other solutions besides HashMap? Is it feasible to use DBObject? Or have other suggestions

2. when i use HashMap or DBObject,the return data like:
```
[
    {
        "updateDate": 1621329448409,
        "isDelete": false,
        "name": "test",
        "_id": "b8261207-3f95-40ca-bd05-e06ad451dff8",
        "receivedDate": 1621071532000,
        "deviceId": "55118b35-43d3-4700-b8be-41daefb7f502",
        "createDate": 1621329448409
    }
]
```

the date format is not good, i want to get  "yyyy-MM-dd HH:mm:ss"
Is there a way to automatically convert the format? It is not a good solution to use traversal processing

**Comment by mp911de** [comment]
What is the output if you call `toString()` on `List<HashMap>`? The output above looks like some JSON output that isn't related to Spring Data at all nor can we do there anything as date conversion has to be configured on the JSON mapper level.

**Comment by linrong** [comment]
![image](https://user-images.githubusercontent.com/24383031/118776211-525a2780-b8ba-11eb-9b5c-da8f98989860.png)
when i debug, i see the date in HashMap like that, maybe  I handle it in spring's conversion? Or does spring-data-mongo have a configuration that can set the date format?

also, I should use HashMap or DBObject ? can you get me some suggestins?

**Comment by mp911de** [comment]
Thanks for the details. Spring Data MongoDB doesn't provide means for the presentation layer because it is a database integration library, not a presentation layer library. We generally recommend using proper domain models as you can make use of i.e. Jackson annotations or convert types to a format that you want to use.

Closing this ticket as Spring Data MongoDB isn't the right place to discuss presentation layer issues and we generally use GitHub for bug reports and feature proposals. You might want to check out Stackoverflow for your case.
