### ISSUE TITLE
Cómo conectar Mongodb  a Sqlserver.

### ISSUE THREAD

**Issue by macriolix** [spring-projects/spring-data-mongodb#3667]
Lo que necesito es saber cómo puedo conectar y hacer consulta desde Mongo a sqlserver 2005 para la cual pueda rescatar esa información. Alguna forma como poder lograrlo

**Comment by christophstrobl** [comment]
We're sorry, please report issues in English - Lo sentimos, informe los problemas en inglés.
Nevertheless it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
