### ISSUE TITLE
Saving Map <String, Object> specifying the value type

### ISSUE THREAD

**Issue by 9arth** [spring-projects/spring-data-mongodb#3680]
Sorry for my english. Saving Map <String, Object> specifying the value type, now saving occurs without specifying the value type and during deserialization the value of the type is lost and converted to the default type. For example, they saved the set, but got the list, etc. 
for example(not real) code:

Duration saved how "5M", when deserialize as Object.class type and converters not working.
`@Document(collection = "token_settings")
public class TokenSettingsDoc {

    @MongoId(FieldType.OBJECT_ID)
    private String id;

    private Map<String, Object> settings;
} 

var setExample = new HashSet<String>();
setExample.add("testValue");
var settings = new HashMap<String, Object>();
settings.put("durationExample", Duration.ofMinutes(5));
settings.put("setExample", setExample);

var tokenSettings = new TokenSettingsDoc()
tokenSettings.setSettings(settings);`

After read values from db TokenSettingsDoc tokenSettings: 
` Set<String> sets = tokenSettings.getSettings().get("setExample"); // ClassCastException  since there is already a list`

**Comment by divyajnu08** [comment]
Hi Mark/Christoph

I was trying to find out the root cause of this error and found out that Mongo database doesn't support a different structure for sets and while serializing it converts it to list. When spring reads it back from db , the type information(set) is lost and Array List is read. Similarly for Duration class it reads as type string. So after making some conversions finally the object returned is a Map of component types Map<String,ArrayList>. I would like to work on this ticket but struggling for the solution. It would be great if you please guide me on how to proceed on this ?

Thanks

**Comment by christophstrobl** [comment]
This is the expected default behavior when working with `Object` `Map`s holding values that are are not considered domain specific ones. Those will be restored on a best effort basis.
