### ISSUE TITLE
 @query annotations

### ISSUE THREAD

**Issue by heheshang** [spring-projects/spring-data-mongodb#3897]
How to use custom annotations instead of @query annotations

**Comment by christophstrobl** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
