### ISSUE TITLE
onAfterLoad/onAfterConvert callbacks are not invoked on @DocumentReference loaded entities

### ISSUE THREAD

**Issue by caspianb** [spring-projects/spring-data-mongodb#3902]
The "onLoad" lifecycle events for entities do not appear to fire when loaded via a @DocumentReference annotation.

Was this a miss or working as intended?

**Comment by mp911de** [comment]
This is by design as references are assumed to be part of the aggregate root and we trigger only events and callbacks for the root document.

**Comment by caspianb** [comment]
I'm not sure I'm following the explanation here. How are they part of the aggregate root if they're a different collection?

In our specific scenario, we have Many-To-Many style mappings between two different collections. 

As an example data model:
Orders (contains OrderLines) <-> Shipments (containers ShipmentLines which point to an originating OrderLine).

Shipments might be for one or many orders. An order's lines might be split among one or many shipments.

It's helpful to put on the ShipmentLine a @DocumentReference to the original Order it came from. But our Order might have logic we run to "prep" the domain object when we read it in (pass some @Transient references down to children objects, etc, to make the code flow a bit easier in the domain logic). Without the events, we are unable to load and actually use these objects via @DocumentRerference.

**Comment by mp911de** [comment]
> I'm not sure I'm following the explanation here. How are they part of the aggregate root if they're an X-to-One style mapping in a different collection?

`@DocumentReference` is the last resort and not the go-to approach. Imagine a `Blog` aggregate referencing `Comment`s. BSON is limited to 16MB and a popular blog site having millions of comments easily exceeds BSON limits. 
To work around these limitations, comments can be stored in their own collection. From an aggregate perspective, they get loaded with the `Blog` entry.

`@DocumentReference` is **not** a convenience shortcut to avoid a couple of lines of code that would otherwise fetch objects from a different repository.

Linking documents in MongoDB is always a workaround, DBRef's are no exception.
