### ISSUE TITLE
MergeOperation reactive streams support

### ISSUE THREAD

**Issue by apffa** [spring-projects/spring-data-mongodb#3993]
I'd like to know if it is currently possible to use `MergeOperation` with project reactor, and if not I'd like to ask that as a feature request

**Comment by sangyongchoi** [comment]
I think it is possible with ReactiveMongoOperations.

**Comment by apffa** [comment]
@sangyongchoi can you give an example?

**Comment by sangyongchoi** [comment]
sorry. I mistook MergeOperation for mongoOperation

**Comment by christophstrobl** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Nevertheless, you can use `ReactiveMongoOperations#aggregate(...)` to run aggregations incl. the `$merge` stage. In that regard `AggregationOptions#skipOutput()` may also prove handy.

**Comment by apffa** [comment]
Hey @christophstrobl, thanks for the quick response. I've posted a SO question before the issue, see [here](https://stackoverflow.com/questions/71455779/reactive-spring-data-mongo-merge-operation).
