### ISSUE TITLE
DataAccessResourceFailureException

### ISSUE THREAD

**Issue by sunnycalsoft** [spring-projects/spring-data-mongodb#4202]
```
{"time":"2022-10-12T04:16:41,766Z","level":"ERROR","thread":"https-jsse-nio-8080-exec-2","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 120000 ms while waiting for a connection to server psmdb-db-mongos.mongodb:27017.; nested exception is com.mongodb.MongoTimeoutException: Timed out after 120000 ms while waiting for a connection to server psmdb-db-mongos.mongodb:27017.] with root cause","context":"default","exception":"com.mongodb.MongoTimeoutException: Timed out after 120000 ms while waiting for a connection to server psmdb-db-mongos.mongodb:27017.
\tat com.mongodb.internal.connection.DefaultConnectionPool.createTimeoutException(DefaultConnectionPool.java:330)
\tat com.mongodb.internal.connection.DefaultConnectionPool.access$2000(DefaultConnectionPool.java:106)
\tat com.mongodb.internal.connection.DefaultConnectionPool$OpenConcurrencyLimiter.acquirePermitOrGetAvailableOpenedConnection(DefaultConnectionPool.java:1003)
\tat com.mongodb.internal.connection.DefaultConnectionPool$OpenConcurrencyLimiter.openAsyncWithConcurrencyLimit(DefaultConnectionPool.java:941)
\tat com.mongodb.internal.connection.DefaultConnectionPool.lambda$getAsync$1(DefaultConnectionPool.java:231)
\tat com.mongodb.internal.connection.DefaultConnectionPool$Task.doComplete(DefaultConnectionPool.java:1385)
\tat com.mongodb.internal.connection.DefaultConnectionPool$Task.execute(DefaultConnectionPool.java:1371)
\tat com.mongodb.internal.connection.DefaultConnectionPool$AsyncWorkManager.workerRun(DefaultConnectionPool.java:1311)
\tat com.mongodb.internal.connection.DefaultConnectionPool$AsyncWorkManager.runAndLogUncaught(DefaultConnectionPool.java:1342)
\tat com.mongodb.internal.connection.DefaultConnectionPool$AsyncWorkManager.lambda$initUnlessClosed$0(DefaultConnectionPool.java:1275)
\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)
\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
\tat java.base/java.lang.Thread.run(Unknown Source)
","correlation-id":"","source-ms":"","user-id":"","user-role":"","additional-info":""}
{"time":"2022-10-12T04:16:41,768Z","level":"INFO","thread":"https-jsse-nio-8080-exec-2","logger":"com.radisys.macs.cems.common.mdclogin.LoggerInterceptor","message":"thread name for MDC Task pre handle: https-jsse-nio-8080-exec-2","context":"default","correlation-id":"","source-ms":"","user-id":"","user-role":"","additional-info":""}
```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
            <version>2.7.0</version>
        </dependency>

Getting this error after application run 30-40 minutes then it restarts and application starts working

**Comment by sunnycalsoft** [comment]
@jyemin yes the problem is that even health check failed for mongodb in the application and application gets restarted.

**Comment by stIncMale** [comment]
@sunnycalsoft The presented `com.mongodb.MongoTimeoutException`s originating from `DefaultConnectionPool` don't by themselves signify a driver problem. They happen when the pool is asked for a connection, but does not have enough [available](https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#marking-a-connection-as-available-internal-implementation) non-[perished](https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#:~:text=it%20is%20possible%20for%20a%20Connection%20to%20become%20Perished) connections. When this happens, the pool tries to [create](https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#creating-a-connection-internal-implementation) and [establish](https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#establishing-a-connection-internal-implementation) a new connection. The former is constrained by pool's [max size](https://mongodb.github.io/mongo-java-driver/4.7/apidocs/mongodb-driver-core/com/mongodb/connection/ConnectionPoolSettings.html#getMaxSize()), the latter is constrained by pool's [max connecting limit](https://mongodb.github.io/mongo-java-driver/4.7/apidocs/mongodb-driver-core/com/mongodb/connection/ConnectionPoolSettings.html#getMaxConnecting()). The stack traces have the `acquirePermitOrGetAvailableOpenedConnection` frame, which tells that the activity of checking out a connection has passed the max size barrier (though it is unknown how much of the [checkout timeout](https://mongodb.github.io/mongo-java-driver/4.7/apidocs/mongodb-driver-core/com/mongodb/connection/ConnectionPoolSettings.html#getMaxWaitTime(java.util.concurrent.TimeUnit)) it spent there, maybe most of it), but failed to pass the max connecting barrier within the rest of the timeout (passing this barrier happens either because the pool allows the checkout request to establish a connection, or because a different connection was checked in the pool and was not checked out by a different request that had also been waiting on this barrier).

I can think of two situations that may cause the exception:

1. The pool is actually working at / close to its capacity (max size), and connections stay checked for long a long time because MongoDB commands they are used for are time-consuming. You may see pool's `checkedOutCount`, `size`, `maxSize` via JMX as described [here](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/monitoring/#monitor-connection-pool-events-with-jmx). If the pool actually operates at / close to its capacity, you may try to increase the max size. 
2. The driver [cleared](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-monitoring.rst#clear-the-connection-pool-on-both-network-and-command-errors) the pool at some point, and when the driver decides to use the pool again, not all checkout requests that flood the pool can be satisfied in a timely manner given the configured max connecting limit. You may try and increase this limit.

Hopefully the above will help. If it won't, and your company has support from MongoDB, then, of course, you may want to create a support case.

**Comment by mp911de** [comment]
This ticket relates to MongoDB driver internals and nothing that we can handle from the Spring Data side.
