### ISSUE TITLE
AbstractMongoEventListener does not support the update type of Mongotemplate

### ISSUE THREAD

**Issue by Jon-Gaara** [spring-projects/spring-data-mongodb#4291]
I want to intercept the write request of mongodb, but I found that both AbstractMongoEventListener and @EnableMongoAuditing cannot work properly when implementing the update type of Mongotemplate. 
I would like to ask, is there a plan for AbstractMongoEventListener and @EnableMongoAuditing to support the update type of Mongotemplate?
![1676450923295](https://user-images.githubusercontent.com/7116647/218978646-6490e371-bccd-42b8-8361-da0fafa31fc1.png)

**Comment by mp911de** [comment]
Neither regular update queries (`Update` object) nor bulk update queries make use of auditing/event listeners. This is, because the query is ran on the MongoDB server passing on only the changes. The actual update happens on the MongoDB server without us ever seeing the updated document.

Therefore, we do not have any update events to be surfaced to listeners or entity callbacks.

Entity listeners work only for saving or updating entire domain objects, where you provide the actual object (`OnlineProductEx`) to `MongoTemplate` as Spring Data MongoDB is sending the full document to MongoDB and Spring Data can provide auditing updates based on the object.

**Comment by Jon-Gaara** [comment]
So is there any way to intercept update type requests in spring-data-mongodb? I can’t find it in the documentation

**Comment by mp911de** [comment]
The only thing that would come close to intercepting updates is overriding the `protected UpdateResult doUpdate(…)` method of `MongoTemplate`

**Comment by Jon-Gaara** [comment]
ok,thanks
