### ISSUE TITLE
When an entity loads a field marked as lazy, the LazyLoadingProxy remains.

### ISSUE THREAD

**Issue by fab918** [spring-projects/spring-data-mongodb#4331]
Some context:

In order to limit the number of queries I mark the @DbRef fields of my entities as lazy.

However when Spring Boot, in the context of an API Rest, transforms the entity into JSON, it will trigger the loading of the proxy, which is normal.

That's why I want to load in my persistence service the lazy fields, dynamically when it's needed. And then in a custom `JsonSerializer` dynamically exclude the field if it has not been loaded/resolved. (if the object is a `LazyLoadingProxy`)

However, even when the field is loaded, it remains a `LazyLoadingProxy` without any way to know if the field was loaded or not.

It feel weird because the proxy has done its job , I thought that after loading the proxy is replaced by the normal object.

if this is the desired behaviour, should we add a method in the `LazyLoadingProxy` to know, if the proxy is resolved or not?  Or is there a way to find out this information?

**Comment by christophstrobl** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Nevertheless, this is the intended behaviour. 
To read the loading state you'd need to obtain the `LazyLoadingInterceptor` and retrieve its `resolved` field.
I'd not recommend this strategy as you'd be reflectively accessing internal fields and state that do not have any API contract. Maybe you can create a dynamic projection that only loads the fields you need in first place.
