### ISSUE TITLE
[Question] - Version

### ISSUE THREAD

**Issue by Lucasark** [spring-projects/spring-data-mongodb#4569]
When we use @version to handle optmist lock, what happened when it is 2147483647, or max number expression in Long?
In the most example @Version is used with Long and in MongoDB is converted to Int32.

**Comment by christophstrobl** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

However, in this case any save operation will fail with a `Write operation error` since the `$inc` operation cannot increase the field value beyond its boundaries.
