### ISSUE TITLE
springboot1.5 not compatible  Spring-data-mongoDB 3.4.18？

### ISSUE THREAD

**Issue by heiminet** [spring-projects/spring-data-mongodb#4617]
How to make Spring Boot 1.5 compatible with Spring Data MongoDB 3.4.18? I couldn't find a version that fixes the vulnerability.

**Comment by christophstrobl** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Please note that `spring-boot:1.5.x` is out of support since mid 2019. Also `data-mongodb:3.4.x` has already passed its support lifetime.
