### ISSUE TITLE
ReactiveMongoRepository save() does not return the persisted object

### ISSUE THREAD

**Issue by Poundex** [spring-projects/spring-data-mongodb#4847]
When calling the `save()` method I expect the returned object to be the object that was persisted in the database. However, I am finding that the returned object isn't the object as it was persisted, it is a copy of the object I passed in to be saved with its ID filled in. Things could happen in the database which mean this is not always the case (this is acknowledged by the documentation, which both specifies that the return value will be the object as persisted, and that this return value should be used for further processing as things may have changed in the database). 

I ran into this issue because of the limited precision of Mongo's `ISODateTime`, although there are probably many other cases where this can happen. 

Reproducer with failing test:
[mongoentityissue.zip](https://github.com/user-attachments/files/18023841/mongoentityissue.zip)

**Comment by mp911de** [comment]
> When calling the save() method I expect the returned object to be the object that was persisted in the database. However, I am finding that the returned object isn't the object as it was persisted, it is a copy of the object I passed in to be saved with its ID filled in.

That is our definition of persisted object: Anything that happens inside the Java runtime applying mutations to the object is what you get as return object.

Anything that happens in the database isn't visible to the returned object. Otherwise, we would have to retrieve that object (read-after-write). We cannot make such assumptions on our side as all database activity like triggers are opaque to us. If you want to retrieve the object state after database triggers happened, then you need to retrieve that object after write yourself.

Btw: Using richer data types on the JVM (Java 9 introduced nano-second precision to JSR 310 types which is quite nasty for equality checks) is always asking for trouble.
